swagger: "2.0"
info:
  version: 1.0.0
  title: Authentication API
  description: A simple authentication API made with nodejs
schemes: 
  - http
host: localhost:3000
basePath: /api
paths:
  /user/login:
    post:
      tags: 
        - Authentication
      summary: Log in
      description: Log in to the application with and existing user
      produces: 
        - application/json
      parameters:
        - name: user
          in: body
          description: The user who wants to log in in the application
          schema:
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: User logged in
          schema:
            type: object
            properties:
              token:
                type: string
                description: The user's token
        400:
          description: The email or password is wrong
          schema:
            type: object
            properties:
              error:
                type: string
                description: Brief information about the error
  /user/register:
    post:
      tags:
        - Authentication
      summary: It registers a new user
      description: End point that allows a new user to sign up in the application
      produces: 
        - application/json
      parameters:
        - name: new user
          in: body
          description: The new user who wants to sign up in the application
          schema:
            required:
              - name
              - email
              - password
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: User created
          schema:
            type: object
            properties:
              userId:
                type: string
                description: The recently new user id
                example: 5f1deccb4335273d9009bj84
        400:
          description: The name, email or password is wrong
          schema:
            type: object
            properties:
              error:
                type: string
                description: Brief information about which field is wrong
                example: \"name\" length must be at least 6 characters long
        409:
          description: The email already exists
          schema:
            type: object
            properties:
              error:
                type: string
                description: Brief information about the error
                example: The email already exists
                
                
          
        
              
        
      
          

                
      
  